environment:
    CLI_VERSION: latest
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOCUMENT_DB_URI: https://localhost:8081
    DOCUMENT_DB_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
image: Visual Studio 2019
configuration:
    - Release
install:
    - ps: $DebugPreference = 'Continue'
    - ps: Import-Module "C:\Program Files\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
    - ps: Start-CosmosDbEmulator -NoUI -Timeout 0
before_build:
    - dotnet tool install -g GitVersion.Tool
    - dotnet gitversion /l console /output buildserver
build_script:
    - dotnet build -c Release -p:Version=%GitVersion_NuGetVersion%
test_script:
    - dotnet test -c Release --no-build
artifacts:
    - name: NuGet
      path: .\**\*.nupkg
    - name: Symbols
      path: .\**\*.snupkg
deploy:
    - provider: NuGet
      api_key:
        secure: +CD+4G+gMInD/BjNvO24NW9u1udGdsx0fUi6bh0muNezQ9fP0sHnS1f96f0OXUy6
      on:
        branch:
            - master
            - /release\/[0-9]\.[0-9]/
